### ISSUE TITLE
AccessViolationException  for Client 4.0

### ISSUE THREAD

**Issue by marcindzwonnik** [checkout/checkout-net-library#20]
Hi,

When I run following code using client for .net 4.0 i am getting AccessViolationException , the same code with the same configuration for .net 4.5 client works fine.

  var paymentTokenRequest = new PaymentTokenCreate()
            {
                Currency = "GBP",
                Value = "100",
                Email = "user@hotmail.com",
                ChargeMode = 1,
                AutoCapTime = 1,
                AutoCapture = "N",
                Products = new List<Product>()
            };
            var ckoApiClient = new APIClient();

            // Submit your request and receive an apiResponse
            var apiResponse = ckoApiClient.TokenService.CreatePaymentToken(paymentTokenRequest);

An exception is thrown when httpClient does SendAsync

System.AccessViolationException was unhandled by user code
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=System
  StackTrace:
       at System.Net.WebRequest.InternalSetCachePolicy(RequestCachePolicy policy)
       at System.Net.WebRequest.set_CachePolicy(RequestCachePolicy value)
       at System.Net.Http.WebRequestHandler.InitializeWebRequest(HttpRequestMessage request, HttpWebRequest webRequest)
       at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
       at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
       at Checkout.ApiHttpClient.SendRequest[T](HttpRequestMessage request)
       at Checkout.ApiHttpClient.PostRequest[T](String requestUri, String authenticationKey, Object requestPayload)
       at Checkout.ApiServices.Tokens.TokenService.CreatePaymentToken(PaymentTokenCreate requestModel)
       at CheckoutSample.Controllers.HomeController.Index() in C:\Users\Marcin\documents\visual studio 2010\Projects\CheckoutSample\CheckoutSample\Controllers\HomeController.cs:line 39
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClassd.<InvokeActionMethodWithFilters>b__a()
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
  InnerException: 

Any ideas?

Regards,
Marcin

**Comment by nicolas-maalouf-cko** [comment]
Dear @marcindzwonnik 

Sorry for the delay in getting back to you.

To help us replicate the issue on our side, could you please get back to us on the below points?

1. Are you running both the 4.0 and 4.5 clients on the same machine?
2. Are you on a 32-bit or 64-bit environment?

Also any additional details about your environment may help us.

Thanks
